### ISSUE TITLE
"Unexpected token u in JSON at position 0" when call event without payload

### ISSUE THREAD

**Issue by evilfant** [effector/logger#62]
[codesandbox](https://codesandbox.io/s/wizardly-babbage-z2ihj?file=/src/App.tsx)

<details>
  <summary>stacktrace</summary>
  ```
  
  
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at eval (https://z2ihj.csb.app/node_modules/effector-inspector/index.mjs:1844:20)
    at be (https://z2ihj.csb.app/node_modules/effector/effector.mjs:1067:71)
    at et (https://z2ihj.csb.app/node_modules/effector/effector.mjs:1194:12)
    at o (https://z2ihj.csb.app/node_modules/effector/effector.mjs:318:61)
    at Function.create (https://z2ihj.csb.app/node_modules/effector/effector.mjs:386:19)
    at r (https://z2ihj.csb.app/node_modules/effector/effector.mjs:380:22)
    at onClick (https://z2ihj.csb.app/src/App.tsx:36:40)
    at HTMLUnknownElement.callCallback (https://z2ihj.csb.app/node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (https://z2ihj.csb.app/node_modules/react-dom/cjs/react-dom.development.js:3994:16)
    at invokeGuardedCallback (https://z2ihj.csb.app/node_modules/react-dom/cjs/react-dom.development.js:4056:31)
    at invokeGuardedCallbackAndCatchFirstError (https://z2ihj.csb.app/node_modules/react-dom/cjs/react-dom.development.js:4070:25)
    at executeDispatch (https://z2ihj.csb.app/node_modules/react-dom/cjs/react-dom.development.js:8243:3)
    at processDispatchQueueItemsInOrder (https://z2ihj.csb.app/node_modules/react-dom/cjs/react-dom.development.js:8275:7)
    at processDispatchQueue (https://z2ihj.csb.app/node_modules/react-dom/cjs/react-dom.development.js:8288:5)
    at dispatchEventsForPlugins (https://z2ihj.csb.app/node_modules/react-dom/cjs/react-dom.development.js:8299:3)
    at eval (https://z2ihj.csb.app/node_modules/react-dom/cjs/react-dom.development.js:8508:12)
    at batchedEventUpdates$1 (https://z2ihj.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22396:12)
    at batchedEventUpdates (https://z2ihj.csb.app/node_modules/react-dom/cjs/react-dom.development.js:3745:12)
    at dispatchEventForPluginEventSystem (https://z2ihj.csb.app/node_modules/react-dom/cjs/react-dom.development.js:8507:3)
    at attemptToDispatchEvent (https://z2ihj.csb.app/node_modules/react-dom/cjs/react-dom.development.js:6005:3)
    at dispatchEvent (https://z2ihj.csb.app/node_modules/react-dom/cjs/react-dom.development.js:5924:19)
    at unstable_runWithPriority (https://z2ihj.csb.app/node_modules/scheduler/cjs/scheduler.development.js:468:12)
    at runWithPriority$1 (https://z2ihj.csb.app/node_modules/react-dom/cjs/react-dom.development.js:11276:10)
    at discreteUpdates$1 (https://z2ihj.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22413:14)
    at discreteUpdates (https://z2ihj.csb.app/node_modules/react-dom/cjs/react-dom.development.js:3756:12)
    at dispatchDiscreteEvent (https://z2ihj.csb.app/node_modules/react-dom/cjs/react-dom.development.js:5889:3)
    ```
</details>  

effector version: 22.1.2
effector-logger version: 0.13.0

**Comment by evilfant** [comment]
duplicate https://github.com/effector/logger/issues/55
